// flow-typed signature: 3429065b0f11f49e5ec6d76a09741ac8
// flow-typed version: <<STUB>>/stylelint-config-recommended-scss_v^3.1.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-recommended-scss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-recommended-scss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylelint-config-recommended-scss/index' {
  declare module.exports: $Exports<'stylelint-config-recommended-scss'>;
}
declare module 'stylelint-config-recommended-scss/index.js' {
  declare module.exports: $Exports<'stylelint-config-recommended-scss'>;
}
